### ISSUE TITLE
CORS Message in Angular Implementation

### ISSUE THREAD

**Issue by jeroensmink98** [broodroosterdev/WindesheimtoiCal#1]
Hey, I tried to implement your solution into my Angular Project using the Angular HttpClientModule. Everytime i make a Http Get request it will respond in a 405 code. Even when i add the right http headers to the call.

[ LINK TO IMAGE](https://ibb.co/tPqbzQY)

How are you allowed to make get requests to the api?

`const httpOptions = {
  headers: new HttpHeaders({ `
`
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin' : '*',
    'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,OPTIONS',
    'User-Agent': 'request'
  })
};`

`private apiUrl = 'http://api.windesheim.nl/api/klas/ICTSE1b/les';`
`getRoosterData() {
    return this.http.get(this.apiUrl,  httpOptions);
  }`

**Comment by broodroosterdev** [comment]
Firstly, thank you for your interest into the project.

The fact that you are using the api in Angular.js on the client-side presents us with a few more challenges compared to calling it server-side.

To try and figure out what the issue is i tried sending the same exact get-request via a program called Postman.
[This is the result](https://ibb.co/1XWBPJx)

As you can see, i am perfectly able to get information via the api in that matter.
The difference is however, that you are dealing with calling the api in a browser. Due to the fact that the domain of the API is different to that of the site, the browser will check if you have permission from the website to call that api via the [CORS mechanism](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). The CORS mechanism works via a fairly simple permission model: When the user first accesses the main website, the webserver of that website will send a few extra headers which tell the browser which domains they are allowed to get data from. 
`'Access-Control-Allow-Origin' : '*', 'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,OPTIONS'` <- these headers for example

To give the users of your main Angular site permission to call the api, the server will need to send those headers to the users (not the api as you showed in your example). This will indicate to the browser of the users "Hey, you are allowed to get data from every domain, im completely cool with it."  and the browser will happily send and recieve data from the API.

So, what is in your case needed to get the API to work? Firstly, try to host the angular site using a webserver such as apache or nginx. Then, change the settings of the webserver to let them send those CORS headers to the users. [A handy guide can be found here](https://enable-cors.org/server.html) 

I hope this fixed your issue. If it did, please reply to this post. If it didn't, feel free to ask any questions or to post any errors.

**Comment by jeroensmink98** [comment]
Hello, Thankyou for the response. 

i will try to implement the solution as you described in the response.

Currently there is not much to show I only just started developing a "Rooster-Service :chicken:"  after i implemented some features and made a GUI i will make the project Open-Source. propbably after the weekend

I will keep you updated.

**Comment by jeroensmink98** [comment]
Made an proof of concept [public](https://github.com/jeroensmink98/WindesheimSchedule)
